services:
  redis:
    image: redis:7-alpine
    container_name: learnsync-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - learnsync_redis_data:/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: learnsync-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - learnsync_rabbitmq_data:/var/lib/rabbitmq

volumes:
  learnsync_redis_data:
  learnsync_rabbitmq_data:
