import uuid
from unittest.mock import MagicMock, patch
import pytest

from backend.app.core.config import settings
from backend.app.schemas.adaptive import (
    AcademicDiscipline,
    GroundingCitation,
    LearningStyle,
    StudyArtifactType,
)
from backend.app.schemas.workload import WorkloadMode
from backend.app.services.llm import (
    OpenRouterService,
    OpenRouterUnavailableError,
)
from backend.app.services.learner_agents import (
    AgentSynthesisContext,
    AuditoryLearnerAgent,
    KinestheticLearnerAgent,
    LearnerAgentOrchestrator,
    ReadWriteLearnerAgent,
    VisualLearnerAgent,
    learner_agent_orchestrator,
)
from backend.app.services.rag import AdaptiveLearningEngine


# ---------------------------------------------------------------------------
# 1. OpenRouter Free Tier Service & Resilience Tests
# ---------------------------------------------------------------------------

def test_openrouter_unconfigured_raises_unavailable():
    service = OpenRouterService(api_key="")
    assert not service.is_configured()

    with pytest.raises(OpenRouterUnavailableError, match="not configured"):
        service.generate_text("Explain photosynthesis")


def test_openrouter_mock_successful_generation():
    service = OpenRouterService(api_key="sk-or-v1-mock-test-key", model_name="meta-llama/llama-3.3-70b-instruct:free")
    assert service.is_configured()

    mock_response = MagicMock()
    mock_response.status_code = 200
    mock_response.json.return_value = {
        "choices": [
            {
                "message": {
                    "role": "assistant",
                    "content": "Deep conceptual breakdown generated by OpenRouter Free Tier model."
                }
            }
        ]
    }

    with patch("httpx.Client") as mock_client_cls:
        mock_client = MagicMock()
        mock_client.__enter__.return_value = mock_client
        mock_client.post.return_value = mock_response
        mock_client_cls.return_value = mock_client

        output = service.generate_text("Synthesize a clinical trial summary")
        assert "OpenRouter Free Tier model" in output
        mock_client.post.assert_called_once()
        call_kwargs = mock_client.post.call_args[1]
        assert call_kwargs["headers"]["Authorization"] == "Bearer sk-or-v1-mock-test-key"
        assert call_kwargs["json"]["model"] == "meta-llama/llama-3.3-70b-instruct:free"


# ---------------------------------------------------------------------------
# 2. Subagent Spawning Pattern Tests
# ---------------------------------------------------------------------------

@pytest.fixture
def base_context():
    return AgentSynthesisContext(
        folder_id=uuid.uuid4(),
        topic="Myocardial Infarction",
        discipline=AcademicDiscipline.MEDICINE,
        workload_mode=WorkloadMode.FREE,
        context_summary="Emergency triage and management of acute myocardial infarction.",
        citations=[GroundingCitation(chunk_id=uuid.uuid4(), snippet="ST-elevation on 12-lead ECG", document_id=uuid.uuid4())],
        source_chunk_ids=[uuid.uuid4()],
        confidence=0.94,
    )


def test_orchestrator_subagent_registry():
    orchestrator = LearnerAgentOrchestrator()
    agents = orchestrator.get_registered_agents()
    assert "VisualLearnerAgent" in agents
    assert "AuditoryLearnerAgent" in agents
    assert "ReadWriteLearnerAgent" in agents
    assert "KinestheticLearnerAgent" in agents
    assert len(agents) == 4


def test_orchestrator_spawns_visual_subagent(base_context):
    orchestrator = LearnerAgentOrchestrator()
    artifact = orchestrator.spawn_agent(LearningStyle.VISUAL, base_context)

    assert artifact.learning_style == LearningStyle.VISUAL
    assert artifact.artifact_type == StudyArtifactType.MIND_MAP
    assert "mindmap" in artifact.content
    assert artifact.metadata.diagram_syntax == "mermaid"
    assert "flowchart TD" in artifact.metadata.alternative_diagram_syntax
    assert artifact.metadata.concept_tree is not None
    assert artifact.metadata.academic_discipline == AcademicDiscipline.MEDICINE


def test_orchestrator_spawns_auditory_subagent(base_context):
    orchestrator = LearnerAgentOrchestrator()
    artifact = orchestrator.spawn_agent(LearningStyle.AUDITORY, base_context)

    assert artifact.learning_style == LearningStyle.AUDITORY
    assert artifact.artifact_type == StudyArtifactType.AUDIO_SCRIPT
    assert "Professor" in artifact.metadata.speakers
    assert "Student" in artifact.metadata.speakers
    assert artifact.metadata.audio_duration_seconds == 180


def test_orchestrator_spawns_read_write_subagent(base_context):
    orchestrator = LearnerAgentOrchestrator()
    artifact = orchestrator.spawn_agent(LearningStyle.READ_WRITE, base_context)

    assert artifact.learning_style == LearningStyle.READ_WRITE
    assert "Study Guide" in artifact.content


def test_orchestrator_spawns_kinesthetic_subagent_clinical(base_context):
    orchestrator = LearnerAgentOrchestrator()
    artifact = orchestrator.spawn_agent(LearningStyle.KINESTHETIC, base_context)

    assert artifact.learning_style == LearningStyle.KINESTHETIC
    assert artifact.artifact_type == StudyArtifactType.CLINICAL_SIMULATION
    sim = artifact.metadata.simulation_payload
    assert sim.kinesthetic_type == "clinical_simulation"
    assert len(sim.steps) == 3
    assert sim.steps[0].vitals_or_state is not None
    assert "BP" in sim.steps[0].vitals_or_state


# ---------------------------------------------------------------------------
# 3. Concurrent Multi-Subagent Fan-Out (spawn_all_subagents)
# ---------------------------------------------------------------------------

def test_orchestrator_parallel_fan_out(base_context):
    """
    Tests parallel concurrent execution: orchestrator spawns and executes
    all 4 subagents simultaneously via ThreadPoolExecutor.
    """
    artifacts_map = learner_agent_orchestrator.spawn_all_subagents(base_context, max_workers=4)

    assert len(artifacts_map) == 4
    assert LearningStyle.VISUAL in artifacts_map
    assert LearningStyle.AUDITORY in artifacts_map
    assert LearningStyle.READ_WRITE in artifacts_map
    assert LearningStyle.KINESTHETIC in artifacts_map

    # Validate distinct artifacts synthesized by distinct subagents
    assert artifacts_map[LearningStyle.VISUAL].artifact_type == StudyArtifactType.MIND_MAP
    assert artifacts_map[LearningStyle.AUDITORY].artifact_type == StudyArtifactType.AUDIO_SCRIPT
    assert artifacts_map[LearningStyle.READ_WRITE].artifact_type == StudyArtifactType.SUMMARY_NOTE
    assert artifacts_map[LearningStyle.KINESTHETIC].artifact_type == StudyArtifactType.CLINICAL_SIMULATION


def test_adaptive_learning_engine_generate_all_artifacts_integration():
    """
    Tests AdaptiveLearningEngine.generate_all_artifacts endpoint integration.
    """
    f_id = uuid.uuid4()
    chunks = [
        {
            "id": uuid.uuid4(),
            "content": "Patient triage protocol and clinical presentation in myocardial infarction.",
            "cosine_similarity": 0.89,
        }
    ]

    all_artifacts = AdaptiveLearningEngine.generate_all_artifacts(
        folder_id=f_id,
        mode=WorkloadMode.FREE,
        topic="Myocardial Infarction",
        chunks=chunks,
    )

    assert len(all_artifacts) == 4
    for style, artifact in all_artifacts.items():
        assert artifact.folder_id == f_id
        assert artifact.learning_style == style
        assert artifact.topic == "Myocardial Infarction"
        assert not artifact.is_low_confidence
